# Generated by Django 2.2.4 on 2019-09-16 21:40

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mv', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=3, max_digits=6), size=None)),
                ('ma', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=3, max_digits=6), size=None)),
                ('spa', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=3, max_digits=6), size=None)),
                ('cv', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=3, max_digits=6), size=None)),
                ('ise', models.DecimalField(decimal_places=3, max_digits=6)),
                ('iae', models.DecimalField(decimal_places=3, max_digits=6)),
                ('qe', models.DecimalField(decimal_places=3, max_digits=6)),
                ('hre', models.DecimalField(decimal_places=3, max_digits=6)),
                ('hde', models.DecimalField(decimal_places=3, max_digits=6)),
                ('h0', models.DecimalField(decimal_places=3, max_digits=6)),
                ('h1', models.DecimalField(decimal_places=3, max_digits=6)),
                ('h2', models.DecimalField(decimal_places=3, max_digits=6)),
                ('h3', models.DecimalField(decimal_places=3, max_digits=6)),
                ('h4', models.DecimalField(decimal_places=3, max_digits=6)),
                ('cr1', models.DecimalField(decimal_places=3, max_digits=6)),
                ('cr2', models.DecimalField(decimal_places=3, max_digits=6)),
                ('mu', models.DecimalField(decimal_places=3, max_digits=6)),
                ('st', models.DecimalField(decimal_places=3, max_digits=6)),
                ('gauss', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=3, max_digits=6), size=None)),
                ('levy', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=3, max_digits=6), size=None)),
                ('laplace', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=3, max_digits=6), size=None)),
                ('huber', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=3, max_digits=6), size=None)),
                ('histX', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=3, max_digits=6), size=None)),
                ('histY', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=3, max_digits=6), size=None)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loops', to='system.System')),
            ],
        ),
    ]
