# Generated by Django 2.2.5 on 2019-09-29 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loop', '0004_auto_20190917_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='loop',
            name='calculated',
            field=models.BooleanField(default=False),
        ),
    ]
