# Generated by Django 2.2.5 on 2019-10-13 22:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loop', '0005_loop_calculated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loop',
            name='h4',
        ),
        migrations.RemoveField(
            model_name='loop',
            name='mu',
        ),
        migrations.RemoveField(
            model_name='loop',
            name='st',
        ),
        migrations.AddField(
            model_name='loop',
            name='crossX1',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='loop',
            name='crossX2',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='loop',
            name='crossY1',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='loop',
            name='crossY2',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='loop',
            name='haa',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=4, max_digits=15), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='loop',
            name='xp',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=4, max_digits=15), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='loop',
            name='xx',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=4, max_digits=15), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='loop',
            name='yp',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=4, max_digits=15), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='loop',
            name='yy',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=4, max_digits=15), blank=True, null=True, size=None),
        ),
    ]
