# Generated by Django 2.2.6 on 2020-01-05 19:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loop', '0009_auto_20191128_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='loop',
            name='firstApproximation',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=4, max_digits=15), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='loop',
            name='secondApproximation',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=4, max_digits=15), blank=True, null=True, size=None),
        ),
    ]
