# Generated by Django 2.2.6 on 2020-01-06 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loop', '0010_auto_20200105_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='loop',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
