# Generated by Django 2.2.6 on 2020-01-09 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loop', '0012_auto_20200107_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loop',
            name='minKurtosis',
        ),
        migrations.RemoveField(
            model_name='loop',
            name='minSkewness',
        ),
    ]
