# Generated by Django 3.0.2 on 2020-01-17 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loop', '0013_auto_20200109_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='loop',
            name='hausDim',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
    ]
