# Generated by Django 3.0.2 on 2020-01-17 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loop', '0014_loop_hausdim'),
    ]

    operations = [
        migrations.AddField(
            model_name='loop',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
    ]
